### ISSUE TITLE
Push 'dist' directory to 'gh-pages' branch automatically

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/elections-app#1]
Let's use something like Travis CI to do this.

**Comment by AstraLuma** [comment]
GitHub actions automatically has write permissions.

**Comment by AstraLuma** [comment]
Personal notes:

https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

Have a workflow on push and schedule, using the `node` container

0. (Run checkout action)
1. Check out repo with `git clone --depth 1 --branch gh-pages <repo url> /tmp/pages`
2. Run `npm run build-prod`, targetting /tmp/pages as the builddir (or copy after build)
3. Commit & push `/tmp/pages`

**Comment by jacebrowning** [comment]
I'm going to go with Travis CI to get this working today as that's what I'm most familiar with.

**Comment by AstraLuma** [comment]
I said I was going to do it tonight? but ok

**Comment by jacebrowning** [comment]
We want to get it deployed so we can start testing after dinner.
